spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
    #ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  thymeleaf:
#    check-template-location: true
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

logging:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: